export const categoryNames = {
  NEW_ARRIVES: "Novidades",
  CLOTHES: "Roupas",
  SHOES: "Calçados",
  ACCESSORIES: "Acessórios",
  BAGS: "Bolsas",
  BEAUTY: "Beleza",
  HOME: "Casa",
  SPORTS: "Esporte",
  KIDS: "Infantil",
  PROMOTIONS: "Promoções",
  LAUNCHES: "Outlet",
  TRENDS: "Tendências",
  MENS_FASHION: "Moda Masculina",
  WOMENS_FASHION: "Moda Feminina",
  OUTLET: "Lançamentos"
};

export const subcategoryNames = {
  NEW_ARRIVES: [
    "Vestidos",
    "Blusas",
    "Calças",
    "Saias",
    "Casacos",
    "Macacões",
    "Tênis",
    "Sapatos",
    "Botas",
    "Sandálias",
    "Chinelos",
    "Bolsas",
    "Colares",
    "Brincos",
    "Pulseiras",
    "Lenços",
    "Óculos",
    "Cintos",
    "Carteiras",
    "Decoração",
    "Casa",
    "Beleza",
    "Eletrônicos",
    "Exclusivos"
  ],
  CLOTHES: [],
  SHOES: [],
  ACCESSORIES: [],
  BAGS: [],
  BEAUTY: [],
  HOME: [],
  PROMOTIONS: [],
  SPORTS: [],
  KIDS: [],
  ELECTRONICS: []
};
